blank_issues_enabled: false
contact_links:
  - name: NineAnimator Discord Community
    url: https://discord.gg/dzTVzeW
    about: Join our live discussions and receive instantaneous feedback.
  - name: NineAnimator Subreddit
    url: https://www.reddit.com/r/NineAnimator/
    about: Discuss about the app and post your experiences and discoveries.
