#
#  This file is part of the NineAnimator project.
#
#  Copyright © 2018-2020 Marcus Zhou. All rights reserved.
#
#  NineAnimator is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  NineAnimator is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with NineAnimator.  If not, see <http:#www.gnu.org/licenses/>.
#

# A list of devices you want to take the screenshots from
devices([
  "iPhone 11",
  "iPhone 11 Pro",
  "iPhone 11 Pro Max",
  "iPhone 8 Plus",
  "iPhone 8",
  "iPad Pro (9.7-inch)",
  "iPad Pro (11-inch)",
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (3rd generation)"
])

languages([
  "en-US"
])

scheme "ScreenshotAutomation"
project "./NineAnimator.xcodeproj"
clear_previous_screenshots true
dark_mode true
derived_data_path "./fastlane/derived_data"
